from __future__ import annotations

from datetime import date, datetime
from typing import Callable, Protocol, Sequence

from telegram_scraper.kg.models import (
    ChannelProfile,
    ChannelSummary,
    CrossChannelMatch,
    Node,
    NodeCentroidRecord,
    NodeDetail,
    NodeKind,
    NodeListEntry,
    NodeMatch,
    NodeRelation,
    RawMessage,
    StoryEmbeddingRecord,
    StoryMatch,
    StoryNodeAssignment,
    StorySemanticExtraction,
    StorySemanticRecord,
    StoryUnit,
    ThemeDailyStat,
    ThemeHeatSnapshot,
    ThemeHistoryPoint,
)


class StoryRepository(Protocol):
    def ensure_schema(self) -> None: ...

    def upsert_channel_profile(self, profile: ChannelProfile) -> None: ...

    def get_channel_profile(self, channel_id: int) -> ChannelProfile | None: ...

    def list_channels(self) -> list[ChannelSummary]: ...

    def upsert_raw_messages(self, messages: Sequence[RawMessage]) -> None: ...

    def list_unsegmented_raw_messages(self, channel_id: int, *, limit: int | None = None) -> list[RawMessage]: ...

    def list_recent_raw_messages(self, channel_id: int, *, limit: int) -> list[RawMessage]: ...

    def list_raw_messages(self, channel_id: int) -> list[RawMessage]: ...

    def save_raw_message_translations(self, messages: Sequence[RawMessage]) -> None: ...

    def get_last_story_unit(self, channel_id: int) -> StoryUnit | None: ...

    def list_recent_story_units(self, channel_id: int, *, limit: int) -> list[StoryUnit]: ...

    def list_story_units(self, *, channel_id: int | None = None) -> list[StoryUnit]: ...

    def get_story_messages(self, story_id: str) -> list[RawMessage]: ...

    def save_story_units(self, stories: Sequence[StoryUnit]) -> None: ...

    def list_stories_without_semantics(
        self,
        *,
        channel_id: int | None = None,
        limit: int | None = None,
    ) -> list[StoryUnit]: ...

    def get_story_unit(self, story_id: str) -> StoryUnit | None: ...

    def upsert_story_semantics(self, records: Sequence[StorySemanticRecord]) -> None: ...

    def save_semantic_results(
        self,
        *,
        nodes: Sequence[Node],
        assignments: Sequence[StoryNodeAssignment],
        semantics: Sequence[StorySemanticRecord],
        cross_channel_matches: Sequence[CrossChannelMatch] = (),
    ) -> None: ...

    def get_story_semantic_record(self, story_id: str) -> StorySemanticRecord | None: ...

    def save_nodes(self, nodes: Sequence[Node]) -> None: ...

    def get_nodes(self, node_ids: Sequence[str]) -> list[Node]: ...

    def list_nodes(
        self,
        *,
        kind: NodeKind | None = None,
        status: str | None = "active",
        limit: int | None = None,
    ) -> list[Node]: ...

    def get_node_by_slug(self, *, kind: NodeKind, slug: str) -> Node | None: ...

    def save_node_relations(self, relations: Sequence[NodeRelation]) -> None: ...

    def replace_node_relations(self, relations: Sequence[NodeRelation]) -> None: ...

    def list_node_relations(self, node_id: str) -> list[NodeRelation]: ...

    def save_story_node_assignments(self, assignments: Sequence[StoryNodeAssignment]) -> None: ...

    def delete_story_node_assignments(
        self,
        *,
        node_id: str | None = None,
        story_ids: Sequence[str] | None = None,
    ) -> None: ...

    def get_story_node_assignments(self, story_id: str) -> list[StoryNodeAssignment]: ...

    def list_story_node_assignments(
        self,
        *,
        story_ids: Sequence[str] | None = None,
        node_ids: Sequence[str] | None = None,
    ) -> list[StoryNodeAssignment]: ...

    def list_story_node_ids(self, story_id: str) -> list[str]: ...

    def get_story_units_by_ids(self, story_ids: Sequence[str]) -> list[StoryUnit]: ...

    def list_story_ids_for_node_on_date(self, node_id: str, day: date) -> list[str]: ...

    def list_story_ids_for_node(self, node_id: str) -> list[str]: ...

    def list_stories_for_node(self, node_id: str, *, limit: int, offset: int) -> tuple[int, list[tuple[StoryUnit, StoryNodeAssignment]]]: ...

    def save_cross_channel_matches(self, matches: Sequence[CrossChannelMatch]) -> None: ...

    def replace_cross_channel_matches(self, matches: Sequence[CrossChannelMatch]) -> None: ...

    def list_cross_channel_matches(self) -> list[CrossChannelMatch]: ...

    def save_theme_daily_stats(self, stats: Sequence[ThemeDailyStat]) -> None: ...

    def refresh_theme_heat_view(self) -> None: ...

    def delete_nodes(self, node_ids: Sequence[str]) -> None: ...

    def clear_semantic_state(
        self,
        *,
        channel_id: int | None = None,
    ) -> tuple[list[str], list[str], list[str]]: ...

    def clear_story_state(self, *, channel_id: int) -> tuple[list[str], list[str], list[str]]: ...

    def run_with_advisory_lock(self, lock_name: str, callback: Callable[[], None]) -> bool: ...

    def list_theme_heat(self, *, phase: str | None = None, limit: int | None = None) -> list[ThemeHeatSnapshot]: ...

    def get_theme_history(self, *, slug: str) -> list[ThemeHistoryPoint]: ...

    def list_node_entries(
        self,
        *,
        kind: NodeKind,
        limit: int | None = None,
    ) -> list[NodeListEntry]: ...

    def get_node_detail(self, *, kind: NodeKind, slug: str, story_limit: int = 20, story_offset: int = 0) -> NodeDetail | None: ...


class StreamEntry(Protocol):
    entry_id: str
    payload: RawMessage


class RawMessageStream(Protocol):
    def ensure_group(self) -> None: ...

    def add(self, message: RawMessage) -> str: ...

    def read(self, *, consumer_name: str, count: int) -> list[object]: ...

    def ack(self, entry_ids: Sequence[str]) -> None: ...


class Embedder(Protocol):
    def embed_texts(self, texts: Sequence[str]) -> list[list[float]]: ...


class SemanticExtractor(Protocol):
    def extract_story(self, story: StoryUnit) -> StorySemanticExtraction: ...

    def extract_stories(self, stories: Sequence[StoryUnit]) -> list[StorySemanticExtraction]: ...


class MessageTranslator(Protocol):
    def translate_messages(self, messages: Sequence[RawMessage]) -> list[RawMessage]: ...


class VectorStore(Protocol):
    def upsert_story_embeddings(self, records: Sequence[StoryEmbeddingRecord]) -> None: ...

    def update_story_node_ids(self, story_id: str, node_ids: Sequence[str]) -> None: ...

    def fetch_story_embeddings(self, story_ids: Sequence[str]) -> dict[str, list[float]]: ...

    def query_story_embeddings(
        self,
        embedding: list[float],
        *,
        top_k: int,
        exclude_channel_id: int | None = None,
        timestamp_gte: datetime | None = None,
    ) -> list[StoryMatch]: ...

    def upsert_theme_centroids(self, records: Sequence[NodeCentroidRecord]) -> None: ...

    def fetch_theme_centroids(self, node_ids: Sequence[str]) -> dict[str, list[float]]: ...

    def query_theme_centroids(self, embedding: list[float], *, top_k: int) -> list[NodeMatch]: ...

    def upsert_event_centroids(self, records: Sequence[NodeCentroidRecord]) -> None: ...

    def fetch_event_centroids(self, node_ids: Sequence[str]) -> dict[str, list[float]]: ...

    def query_event_centroids(self, embedding: list[float], *, top_k: int) -> list[NodeMatch]: ...

    def delete_story_embeddings(self, story_ids: Sequence[str]) -> None: ...

    def delete_theme_centroids(self, node_ids: Sequence[str]) -> None: ...

    def delete_event_centroids(self, node_ids: Sequence[str]) -> None: ...
